zone: []

messages:
  usage: "§cUsage: /trone <set|remove>"
  point1_set: "§aPoint 1 set at {x}, {y}, {z}. Break another block to set point 2."
  point2_set: "§aPoint 2 set at {x}, {y}, {z}. The Throne zone has been defined."
  zone_removed: "§aThe Throne zone has been removed."
  already_defined: "§cThe Throne zone is already defined."
  trone_enter: "§e{player} has entered the Throne zone!"
  trone_leave: "§e{player} has left the Throne zone."
  trone_money: "§aYou earned {amount} $ for staying in the Throne!"

settings:
  money_per_interval: 10
  interval_seconds: 5
  message_cooldown: 10